# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.protos.auth import auth_pb2 as app_dot_protos_dot_auth_dot_auth__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in app/protos/auth/auth_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AuthStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.register = channel.unary_unary(
                '/Auth/register',
                request_serializer=app_dot_protos_dot_auth_dot_auth__pb2.RegisterRequest.SerializeToString,
                response_deserializer=app_dot_protos_dot_auth_dot_auth__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.login = channel.unary_unary(
                '/Auth/login',
                request_serializer=app_dot_protos_dot_auth_dot_auth__pb2.LoginRequest.SerializeToString,
                response_deserializer=app_dot_protos_dot_auth_dot_auth__pb2.LoginResponse.FromString,
                _registered_method=True)


class AuthServicer(object):
    """Missing associated documentation comment in .proto file."""

    def register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'register': grpc.unary_unary_rpc_method_handler(
                    servicer.register,
                    request_deserializer=app_dot_protos_dot_auth_dot_auth__pb2.RegisterRequest.FromString,
                    response_serializer=app_dot_protos_dot_auth_dot_auth__pb2.RegisterResponse.SerializeToString,
            ),
            'login': grpc.unary_unary_rpc_method_handler(
                    servicer.login,
                    request_deserializer=app_dot_protos_dot_auth_dot_auth__pb2.LoginRequest.FromString,
                    response_serializer=app_dot_protos_dot_auth_dot_auth__pb2.LoginResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Auth', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Auth', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Auth(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Auth/register',
            app_dot_protos_dot_auth_dot_auth__pb2.RegisterRequest.SerializeToString,
            app_dot_protos_dot_auth_dot_auth__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Auth/login',
            app_dot_protos_dot_auth_dot_auth__pb2.LoginRequest.SerializeToString,
            app_dot_protos_dot_auth_dot_auth__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ValidatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.validate = channel.unary_unary(
                '/Validator/validate',
                request_serializer=app_dot_protos_dot_auth_dot_auth__pb2.ValidatorRequest.SerializeToString,
                response_deserializer=app_dot_protos_dot_auth_dot_auth__pb2.ValidatorResponse.FromString,
                _registered_method=True)


class ValidatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def validate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ValidatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'validate': grpc.unary_unary_rpc_method_handler(
                    servicer.validate,
                    request_deserializer=app_dot_protos_dot_auth_dot_auth__pb2.ValidatorRequest.FromString,
                    response_serializer=app_dot_protos_dot_auth_dot_auth__pb2.ValidatorResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Validator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Validator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Validator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def validate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Validator/validate',
            app_dot_protos_dot_auth_dot_auth__pb2.ValidatorRequest.SerializeToString,
            app_dot_protos_dot_auth_dot_auth__pb2.ValidatorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
