# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/protos/auth/auth.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'app/protos/auth/auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x61pp/protos/auth/auth.proto\"Y\n\x0fRegisterRequest\x12\x12\n\nfirst_name\x18\x01 \x01(\t\x12\x11\n\tlast_name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x10\n\x08password\x18\x04 \x01(\t\"\x1e\n\x10RegisterResponse\x12\n\n\x02id\x18\x01 \x01(\x03\"/\n\x0cLoginRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\x1e\n\rLoginResponse\x12\r\n\x05token\x18\x01 \x01(\t\"!\n\x10ValidatorRequest\x12\r\n\x05token\x18\x01 \x01(\t\"%\n\x11ValidatorResponse\x12\x10\n\x08is_valid\x18\x01 \x01(\x08\x32_\n\x04\x41uth\x12/\n\x08register\x12\x10.RegisterRequest\x1a\x11.RegisterResponse\x12&\n\x05login\x12\r.LoginRequest\x1a\x0e.LoginResponse2>\n\tValidator\x12\x31\n\x08validate\x12\x11.ValidatorRequest\x1a\x12.ValidatorResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.protos.auth.auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTERREQUEST']._serialized_start=30
  _globals['_REGISTERREQUEST']._serialized_end=119
  _globals['_REGISTERRESPONSE']._serialized_start=121
  _globals['_REGISTERRESPONSE']._serialized_end=151
  _globals['_LOGINREQUEST']._serialized_start=153
  _globals['_LOGINREQUEST']._serialized_end=200
  _globals['_LOGINRESPONSE']._serialized_start=202
  _globals['_LOGINRESPONSE']._serialized_end=232
  _globals['_VALIDATORREQUEST']._serialized_start=234
  _globals['_VALIDATORREQUEST']._serialized_end=267
  _globals['_VALIDATORRESPONSE']._serialized_start=269
  _globals['_VALIDATORRESPONSE']._serialized_end=306
  _globals['_AUTH']._serialized_start=308
  _globals['_AUTH']._serialized_end=403
  _globals['_VALIDATOR']._serialized_start=405
  _globals['_VALIDATOR']._serialized_end=467
# @@protoc_insertion_point(module_scope)
