# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/protos/pingpong.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'app/protos/pingpong.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x61pp/protos/pingpong.proto\"\x1b\n\x0bPingRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x19\n\tPongReply\x12\x0c\n\x04text\x18\x01 \x01(\t20\n\nPingPonger\x12\"\n\x04Ping\x12\x0c.PingRequest\x1a\n.PongReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.protos.pingpong_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PINGREQUEST']._serialized_start=29
  _globals['_PINGREQUEST']._serialized_end=56
  _globals['_PONGREPLY']._serialized_start=58
  _globals['_PONGREPLY']._serialized_end=83
  _globals['_PINGPONGER']._serialized_start=85
  _globals['_PINGPONGER']._serialized_end=133
# @@protoc_insertion_point(module_scope)
